=== akashgardas/Web-Technologies/Internal/task 9/booksinfo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Title"/>
                            <xs:element name="Author"/>
                            <xs:element name="ISBN"/>
                            <xs:element name="Publisher"/>
                            <xs:element name="Edition"/>
                            <xs:element name="Price"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== akashgardas/Web-Technologies/Internal/task 9/booksinfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="booksinfo.xsd">
    <Book>
        <Title>Java Programming</Title>
        <Author>Akash</Author>
        <ISBN>123456789234</ISBN>
        <Publisher>Hello World</Publisher>
        <Edition>11</Edition>
        <Price>799</Price>
    </Book>

    <Book>
        <Title>Java Programming</Title>
        <Author>Akash</Author>
        <ISBN>123456789234</ISBN>
        <Publisher>Hello World</Publisher>
        <Edition>11</Edition>
        <Price>799</Price>
    </Book>
</Books>
